language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.11"
branches:
  only:
    - gh-pages
before_script:
  - npm install -g grunt-cli
before_install:
 - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] && npm conf set strict-ssl false || true'
